dataset:
  path: data/shakespeare.txt
model:
  block_size: 128
  n_layers: 6
  n_heads: 8
  n_embed: 384
  p_dropout: 0.2
training:
  learning_rate: 3e-4
  batch_size: 64
  n_iterations: 5000
  eval_interval: 500
  eval_iterations: 100
  train_frac: 0.9
  seed: 42
  n_tokens_to_generate_on_eval: 100
  model_save_path: models/shakespeare-babbler.pt
  device: cuda
